# Use the official Node.js image as the base image
FROM node:18-alpine

RUN apk add --no-cache \
    build-base \
    g++ \
    cairo-dev \
    jpeg-dev \
    pango-dev \
    giflib-dev

# Set the working directory
WORKDIR /app

# Copy package.json, package-lock.json, and Jest setup
COPY frontend/package*.json frontend/jest.setup.ts frontend/tsconfig.jest.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code from the frontend directory
COPY frontend/ .

# Build the Next.js application
RUN npm run build

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["npm", "run", "dev"]
#CMD ["npm", "start"]