# Generated by Django 5.0.6 on 2024-08-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tunescript_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userplayhistory",
            name="play_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
