# Generated by Django 5.0.6 on 2024-07-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunescript_app', '0002_userplayhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/default_profile_picture.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
