# Generated by Django 5.0.6 on 2024-08-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tunescript_app", "0002_userplayhistory_play_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcription",
            name="share_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
