# Generated by Django 5.0.6 on 2024-08-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tunescript_app", "0003_transcription_share_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcription",
            name="share_token",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
