# Generated by Django 5.0.6 on 2024-09-14 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tunescript_app", "0004_alter_transcription_share_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rating",
            name="comment",
        ),
    ]
