# Generated by Django 5.0.6 on 2024-10-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tunescript_app", "0005_remove_rating_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transcription",
            name="genre",
        ),
        migrations.AddField(
            model_name="transcription",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="transcriptions", to="tunescript_app.tag"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name="TranscriptionTag",
        ),
    ]
